import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import dynamic from 'next/dynamic';
import { lazy, Suspense } from 'react';

const ReactIFrame = lazy(() => import('@/components/ReactIFrame'));

// const ReactIFrame = dynamic(() => import('@/components/ReactIFrame'), {
// 	suspense: true,
// 	loading: () => <p>loading...</p>
// });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<p className="text-3xl font-medium mt-20">React IFrame</p>
				<br />
				<Suspense fallback="Loading...">
					<ReactIFrame />
				</Suspense>
			</main>
		</>
	);
}
